import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */
import * as enums from '../../enums';

export class InventoryItemCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  quantity: number;
  @ApiProperty()
  unit_price: string;
  @ApiProperty()
  status: enums.InventoryItemStatusEnum;
}

export class InventoryItem {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  quantity: number;
  @ApiProperty()
  unit_price: string;
  @ApiProperty()
  status: enums.InventoryItemStatusEnum;
}
