import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */
import * as enums from '../../enums';

export class SupplierCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  contact_email: string;
  @ApiProperty()
  phone_number: string;
  @ApiProperty()
  address: string;
  @ApiProperty()
  status: enums.SupplierStatusEnum;
}

export class Supplier {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  contact_email: string;
  @ApiProperty()
  phone_number: string;
  @ApiProperty()
  address: string;
  @ApiProperty()
  status: enums.SupplierStatusEnum;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
