/**
 * This file generated by Apso.
 */
export enum SupplierStatusEnum {
  active = 'active',
  inactive = 'inactive',
}
export enum WarehouseStatusEnum {
  active = 'active',
  inactive = 'inactive',
}
export enum InventoryItemStatusEnum {
  in_stock = 'in_stock',
  out_of_stock = 'out_of_stock',
  discontinued = 'discontinued',
}
export enum StockMovementMovementTypeEnum {
  in = 'in',
  out = 'out',
}
