/**
 * This file generated by Apso.
 */
import { SupplierModule } from './Supplier/Supplier.module';
import { WarehouseModule } from './Warehouse/Warehouse.module';
import { InventoryItemModule } from './InventoryItem/InventoryItem.module';
import { StockMovementModule } from './StockMovement/StockMovement.module';

export default [
  SupplierModule,
  WarehouseModule,
  InventoryItemModule,
  StockMovementModule,
];
