import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */
import * as enums from '../../enums';

export class StockMovementCreate {
  @ApiProperty()
  item_id: string;
  @ApiProperty()
  warehouse_id: string;
  @ApiProperty()
  movement_type: enums.StockMovementMovementTypeEnum;
  @ApiProperty()
  quantity: number;
  @ApiProperty()
  movement_date: Date;
}

export class StockMovement {
  @ApiProperty()
  id: number;
  @ApiProperty()
  item_id: string;
  @ApiProperty()
  warehouse_id: string;
  @ApiProperty()
  movement_type: enums.StockMovementMovementTypeEnum;
  @ApiProperty()
  quantity: number;
  @ApiProperty()
  movement_date: Date;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
