import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class OrderCreate {
  @ApiProperty()
  order_date: Date;
  @ApiProperty()
  status: string;
  @ApiProperty()
  total_amount: string;
  @ApiProperty()
  customer_id: number;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}

export class Order {
  @ApiProperty()
  id: number;
  @ApiProperty()
  order_date: Date;
  @ApiProperty()
  status: string;
  @ApiProperty()
  total_amount: string;
  @ApiProperty()
  customer_id: number;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
