import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class CategoryCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
}

export class Category {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
