/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import {
  ArticleCategory,
  ArticleCategoryCreate,
} from './dtos/ArticleCategory.dto';
import { ArticleCategoryController } from './ArticleCategory.controller';
import { ArticleCategoryService } from './ArticleCategory.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('ArticleCategoryController', () => {
  let controller: ArticleCategoryController;
  let spyService: ArticleCategoryService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: ArticleCategoryService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [ArticleCategoryController],
      providers: [ArticleCategoryService, ApiServiceProvider],
    }).compile();

    controller = module.get<ArticleCategoryController>(
      ArticleCategoryController,
    );
    spyService = module.get<ArticleCategoryService>(ArticleCategoryService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call ArticleCategoryController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call ArticleCategoryController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new ArticleCategory();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
