/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { ArticleCategory } from './ArticleCategory.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ArticleCategoryService } from './ArticleCategory.service';
import { ArticleCategoryController } from './ArticleCategory.controller';

@Module({
  imports: [TypeOrmModule.forFeature([ArticleCategory])],
  providers: [ArticleCategoryService],
  exports: [ArticleCategoryService],
  controllers: [ArticleCategoryController],
})
export class ArticleCategoryModule {}
