/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import {
  ArticleCategory,
  ArticleCategoryCreate,
} from './dtos/ArticleCategory.dto';
import { ArticleCategoryService } from './ArticleCategory.service';

@Crud({
  model: {
    type: ArticleCategory,
  },
  dto: {
    create: ArticleCategoryCreate,
    update: ArticleCategory,
    replace: ArticleCategory,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('ArticleCategorys')
@ApiTags('ArticleCategorys')
export class ArticleCategoryController
  implements CrudController<ArticleCategory>
{
  constructor(public service: ArticleCategoryService) {}

  get base(): CrudController<ArticleCategory> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple ArticleCategorys' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single ArticleCategory' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single ArticleCategory' })
  @ApiBody({
    type: ArticleCategoryCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: ArticleCategory,
  ) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multipleArticleCategorys' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<ArticleCategory>,
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single ArticleCategory' })
  update(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: ArticleCategory,
  ) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single ArticleCategory' })
  replace(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: ArticleCategory,
  ) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single ArticleCategory' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
