/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Supplier } from './Supplier.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { SupplierService } from './Supplier.service';
import { SupplierController } from './Supplier.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Supplier])],
  providers: [SupplierService],
  exports: [SupplierService],
  controllers: [SupplierController],
})
export class SupplierModule {}
