/**
 * This file generated by Apso.
 */ /* eslint @typescript-eslint/no-unused-vars: "off" */

import {
  Column,
  Entity,
  CreateDateColumn,
  UpdateDateColumn,
  PrimaryGeneratedColumn,
  Generated,
  JoinColumn,
  JoinTable,
  Index,
  Unique,
  PrimaryColumn,
} from 'typeorm';
import {
  IsOptional,
  IsString,
  MaxLength,
  IsNotEmpty,
  IsEmail,
  IsBoolean,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { CrudValidationGroups } from '@nestjsx/crud';
import * as enums from '../enums';

const { CREATE, UPDATE } = CrudValidationGroups;

@Entity('supplier')
@Index(['name'], { unique: true })
@Unique('unique_contact_email', ['contact_email'])
export class Supplier {
  // Fields
  @PrimaryGeneratedColumn()
  id!: number;

  @CreateDateColumn()
  created_at: Date;

  @UpdateDateColumn()
  updated_at: Date;

  @IsOptional({ groups: [UPDATE] })
  @IsNotEmpty({ groups: [CREATE] })
  @Column({ type: 'varchar', length: 255, nullable: false })
  name: string;

  @IsOptional({ groups: [UPDATE] })
  @IsNotEmpty({ groups: [CREATE] })
  @Column({ type: 'varchar', length: 255, nullable: false })
  contact_email: string;

  @IsOptional({ groups: [UPDATE] })
  @Column({ type: 'varchar', length: 255, nullable: true })
  phone_number: string;

  @IsOptional({ groups: [UPDATE] })
  @Column({ type: 'text', nullable: true })
  address: string;

  @Column({
    type: 'enum',
    enum: enums.SupplierStatusEnum,
    default: enums.SupplierStatusEnum.active,
  })
  status!: enums.SupplierStatusEnum;

  // Associations
}
