import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */
import * as enums from '../../enums';

export class WarehouseCreate {
  @ApiProperty()
  location: string;
  @ApiProperty()
  capacity: number;
  @ApiProperty()
  status: enums.WarehouseStatusEnum;
}

export class Warehouse {
  @ApiProperty()
  id: number;
  @ApiProperty()
  location: string;
  @ApiProperty()
  capacity: number;
  @ApiProperty()
  status: enums.WarehouseStatusEnum;
}
