/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { OrderItem } from './OrderItem.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { OrderItemService } from './OrderItem.service';
import { OrderItemController } from './OrderItem.controller';

@Module({
  imports: [TypeOrmModule.forFeature([OrderItem])],
  providers: [OrderItemService],
  exports: [OrderItemService],
  controllers: [OrderItemController],
})
export class OrderItemModule {}
