/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { OrderItem, OrderItemCreate } from './dtos/OrderItem.dto';
import { OrderItemController } from './OrderItem.controller';
import { OrderItemService } from './OrderItem.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('OrderItemController', () => {
  let controller: OrderItemController;
  let spyService: OrderItemService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: OrderItemService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [OrderItemController],
      providers: [OrderItemService, ApiServiceProvider],
    }).compile();

    controller = module.get<OrderItemController>(OrderItemController);
    spyService = module.get<OrderItemService>(OrderItemService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call OrderItemController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call OrderItemController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new OrderItem();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
