import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class OrderItemCreate {
  @ApiProperty()
  order_id: number;
  @ApiProperty()
  product_id: number;
  @ApiProperty()
  quantity: number;
  @ApiProperty()
  price: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}

export class OrderItem {
  @ApiProperty()
  id: number;
  @ApiProperty()
  order_id: number;
  @ApiProperty()
  product_id: number;
  @ApiProperty()
  quantity: number;
  @ApiProperty()
  price: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
