/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { InventoryItem } from './InventoryItem.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { InventoryItemService } from './InventoryItem.service';
import { InventoryItemController } from './InventoryItem.controller';

@Module({
  imports: [TypeOrmModule.forFeature([InventoryItem])],
  providers: [InventoryItemService],
  exports: [InventoryItemService],
  controllers: [InventoryItemController],
})
export class InventoryItemModule {}
