/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { InventoryItem, InventoryItemCreate } from './dtos/InventoryItem.dto';
import { InventoryItemController } from './InventoryItem.controller';
import { InventoryItemService } from './InventoryItem.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('InventoryItemController', () => {
  let controller: InventoryItemController;
  let spyService: InventoryItemService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: InventoryItemService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [InventoryItemController],
      providers: [InventoryItemService, ApiServiceProvider],
    }).compile();

    controller = module.get<InventoryItemController>(InventoryItemController);
    spyService = module.get<InventoryItemService>(InventoryItemService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call InventoryItemController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call InventoryItemController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new InventoryItem();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
