import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class ArticleCategoryCreate {
  @ApiProperty()
  article_id: string;
  @ApiProperty()
  category_id: string;
}

export class ArticleCategory {
  @ApiProperty()
  id: number;
  @ApiProperty()
  article_id: string;
  @ApiProperty()
  category_id: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
