/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import { Warehouse, WarehouseCreate } from './dtos/Warehouse.dto';
import { WarehouseService } from './Warehouse.service';

@Crud({
  model: {
    type: Warehouse,
  },
  dto: {
    create: WarehouseCreate,
    update: Warehouse,
    replace: Warehouse,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('Warehouses')
@ApiTags('Warehouses')
export class WarehouseController implements CrudController<Warehouse> {
  constructor(public service: WarehouseService) {}

  get base(): CrudController<Warehouse> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple Warehouses' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single Warehouse' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single Warehouse' })
  @ApiBody({
    type: WarehouseCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: Warehouse) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multipleWarehouses' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<Warehouse>,
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single Warehouse' })
  update(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: Warehouse) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single Warehouse' })
  replace(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: Warehouse) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single Warehouse' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
