/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Warehouse } from './Warehouse.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { WarehouseService } from './Warehouse.service';
import { WarehouseController } from './Warehouse.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Warehouse])],
  providers: [WarehouseService],
  exports: [WarehouseService],
  controllers: [WarehouseController],
})
export class WarehouseModule {}
