/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Warehouse, WarehouseCreate } from './dtos/Warehouse.dto';
import { WarehouseController } from './Warehouse.controller';
import { WarehouseService } from './Warehouse.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('WarehouseController', () => {
  let controller: WarehouseController;
  let spyService: WarehouseService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: WarehouseService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [WarehouseController],
      providers: [WarehouseService, ApiServiceProvider],
    }).compile();

    controller = module.get<WarehouseController>(WarehouseController);
    spyService = module.get<WarehouseService>(WarehouseService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call WarehouseController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call WarehouseController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Warehouse();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
