/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { StockMovement } from './StockMovement.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { StockMovementService } from './StockMovement.service';
import { StockMovementController } from './StockMovement.controller';

@Module({
  imports: [TypeOrmModule.forFeature([StockMovement])],
  providers: [StockMovementService],
  exports: [StockMovementService],
  controllers: [StockMovementController],
})
export class StockMovementModule {}
