/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { StockMovement, StockMovementCreate } from './dtos/StockMovement.dto';
import { StockMovementController } from './StockMovement.controller';
import { StockMovementService } from './StockMovement.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('StockMovementController', () => {
  let controller: StockMovementController;
  let spyService: StockMovementService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: StockMovementService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [StockMovementController],
      providers: [StockMovementService, ApiServiceProvider],
    }).compile();

    controller = module.get<StockMovementController>(StockMovementController);
    spyService = module.get<StockMovementService>(StockMovementService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call StockMovementController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call StockMovementController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new StockMovement();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
