/**
 * This file generated by Apso.
 */ /* eslint @typescript-eslint/no-unused-vars: "off" */

import {
  Column,
  Entity,
  CreateDateColumn,
  UpdateDateColumn,
  PrimaryGeneratedColumn,
  Generated,
  JoinColumn,
  JoinTable,
  Index,
  Unique,
  PrimaryColumn,
} from 'typeorm';
import {
  IsOptional,
  IsString,
  MaxLength,
  IsNotEmpty,
  IsEmail,
  IsBoolean,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { CrudValidationGroups } from '@nestjsx/crud';
import * as enums from '../enums';

const { CREATE, UPDATE } = CrudValidationGroups;

@Entity('stock_movement')
@Index(['item_id', 'warehouse_id'])
export class StockMovement {
  // Fields
  @PrimaryGeneratedColumn()
  id!: number;

  @CreateDateColumn()
  created_at: Date;

  @UpdateDateColumn()
  updated_at: Date;

  @Column({ type: 'uuid' })
  item_id: string;

  @Column({ type: 'uuid' })
  warehouse_id: string;

  @Column({
    type: 'enum',
    enum: enums.StockMovementMovementTypeEnum,
    default: enums.StockMovementMovementTypeEnum.in,
  })
  movement_type!: enums.StockMovementMovementTypeEnum;

  @Column({ type: 'int' })
  quantity: number;

  @Column({ type: 'timestamp', nullable: false })
  movement_date: Date;

  // Associations
}
